# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 05:02
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='affiliation',
            field=models.CharField(blank=True, help_text='Optional affiliation, not required for DPaW. If provided, the affiliation will be appended to the person or group name in parentheses.', max_length=200, null=True, verbose_name='Affiliation'),
        ),
        migrations.AddField(
            model_name='user',
            name='agreed',
            field=models.BooleanField(default=False, editable=False, help_text="Has the user agreed to SDIS' Terms and Conditions?", verbose_name='Agreed to the Terms and Conditions'),
        ),
        migrations.AddField(
            model_name='user',
            name='author_code',
            field=models.CharField(blank=True, help_text='The author code links users to their publications. Staff only.', max_length=255, null=True, verbose_name='Author code'),
        ),
        migrations.AddField(
            model_name='user',
            name='curriculum_vitae',
            field=models.TextField(blank=True, help_text='A brief curriculum vitae of academic qualifications and professional memberships.', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='expertise',
            field=models.TextField(blank=True, help_text='A bullet point list of skills and expertise.', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='fax',
            field=models.CharField(blank=True, help_text='The fax number.', max_length=100, null=True, verbose_name='Fax number'),
        ),
        migrations.AddField(
            model_name='user',
            name='group_name',
            field=models.CharField(blank=True, help_text="Group name, if this profile is not a natural person. E.g., 'Goldfields Regional Office'.", max_length=200, null=True, verbose_name='Group name'),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, help_text='If you wish, provide us with a face to the name!', null=True, upload_to='profiles'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_external',
            field=models.BooleanField(default=False, help_text='Is the user external to DPaW?', verbose_name='External to DPaW'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_group',
            field=models.BooleanField(default=False, help_text="Whether this profile refers to a group, rather than a natural person. Groups are referred to with their group name, whereas first and last name refer to the group's contact person.", verbose_name='Show as Group'),
        ),
        migrations.AddField(
            model_name='user',
            name='middle_initials',
            field=models.CharField(blank=True, help_text='Initials of first and middle names. Will be used in team lists with abbreviated names.', max_length=100, null=True, verbose_name='Initials'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='The primary phone number during work hours.', max_length=100, null=True, verbose_name='Primary Phone number'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_alt',
            field=models.CharField(blank=True, help_text='An alternative phone number during work hours.', max_length=100, null=True, verbose_name='Alternative Phone number'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_text',
            field=models.TextField(blank=True, help_text='A profile text for the staff members, roughly three paragraphs long.', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='projects',
            field=models.TextField(blank=True, help_text='Tell us about projects outside SDIS you are involved in.', null=True, verbose_name='Projects outside SDIS'),
        ),
        migrations.AddField(
            model_name='user',
            name='publications_other',
            field=models.TextField(blank=True, help_text='A list of publications produced under external affiliation, in press or otherwise unregistered as staff publication.', null=True, verbose_name='Other publications'),
        ),
        migrations.AddField(
            model_name='user',
            name='publications_staff',
            field=models.TextField(blank=True, help_text='A list of publications produced for the Department. Staff only.', null=True, verbose_name='Staff publications'),
        ),
        migrations.AddField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, help_text='Optional academic title, shown in team lists only if supplied, and only for external team members.', max_length=30, null=True, verbose_name='Academic Title'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, help_text='First name or given name.', max_length=100, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=True, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, help_text='Last name or surname.', max_length=100, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$', 'Enter a valid username.', 'invalid')], verbose_name='username'),
        ),
    ]
